spring:
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:test}
    password: ${RABBITMQ_PASSWORD:test}