project:
  name: spring-cloud-config
spring:
  cloud:
    config:
      override-none: true


---
spring.profiles: dev

project:
  name: dev-spring-cloud-config


---
spring.profiles: prod

project:
  name: prods-spring-cloud-config
